### ISSUE TITLE
Meta hide files bypass

### ISSUE THREAD

**Issue by BoYanZh** [alist-org/alist#2532]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

Any

### Describe the bug / 问题描述

`Hides` in meta does not work for `/api/fs/get`, but only works for `/api/fs/list`. If the attacker can guest the file name of the hidden file with a dictionary, it will cause privacy leakage.

### Reproduction / 复现链接

-

**Comment by BoYanZh** [comment]
Not sure whether it is intended to work like this. The hide function also does not work on Webdav.

**Comment by Xhofe** [comment]
- In the initial design, the default is that the user cannot guess the file name. We can add checks to some api later.
- `hide` would work on webdav when user has no `can_see_hides` permission.

**Comment by BoYanZh** [comment]
The `handles.Down` also can be bypassed, `needSign` seems a little too loose. If there is not a password on the meta apply for the root path, the attacker can still steal the files without a sign once they guess the filename.

**Comment by Xhofe** [comment]
In the past, sign was required for all file downloads, but it seems that later someone said that they need to build the download url through path structure by themselves, so the sign verification without password was removed. Now it seems that it needs to be changed back, or let the user choose.

**Comment by BoYanZh** [comment]
Strongly agree. Some novice users may be attacked by using some default settings.

**Comment by Contribuv** [comment]
> In the past, sign was required for all file downloads, but it seems that later someone said that they need to build the download url through path structure by themselves, so the sign verification without password was removed. Now it seems that it needs to be changed back, or let the user choose.

-------------------------------------------

The developer should add a short link to the API. The sharing path may be Chinese characters. The URL is very long and messy. The short link can solve this problem very well

For example https://alist-org/aliyun/data/Test.tar.gz

https://alist-org/go/xxx
