### ISSUE TITLE
```WebDav``` 成功挂载 ```InfiniCLOUD``` ，但无法正常使用

### ISSUE THREAD

**Issue by signigelchan** [alist-org/alist#4333]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

WebDav

### Describe the bug / 问题描述

通过 ```InfiniCLOUD``` [网页管理界面](https://infini-cloud.net/en/modules/mypage/usage/) 查看 ```WebDAV``` 连接参数， ```Alist``` 成功挂载该云盘。

![InfiniCLOUD_APP](https://user-images.githubusercontent.com/20301894/236689270-71d0f304-ca15-4083-80f4-e64cccf498db.jpeg)

> 注：使用 ```RaiDrive``` 直接挂载网页管理界面显示的对应连接参数，可正常使用。

### Reproduction / 复现链接

通过 ```Alist``` 网页管理 或 ```RaiDrive``` 挂载 ```Alist``` 提供的 ```WebDav``` 方式，
如：创建新的文件夹，文件夹可成功创建，但重命名出错，出现 **```MOVE /InfiniCLOUD: 200```**。

### Logs / 日志

**part 1:**

```
ERRO[2023-05-07 23:30:04] MOVE /dav/InfiniCLOUD/utasch/Others/新建文件夹/ MOVE /Others/新建文件夹: 200
github.com/alist-org/alist/v3/internal/op.Rename
	/app/internal/op/fs.go:412
github.com/alist-org/alist/v3/internal/fs.rename
	/app/internal/fs/other.go:40
github.com/alist-org/alist/v3/internal/fs.Rename
	/app/internal/fs/fs.go:81
github.com/alist-org/alist/v3/server/webdav.moveFiles
	/app/server/webdav/file.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
	/app/server/webdav/webdav.go:459
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:67
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172 
[GIN] 2023/05/07 - 23:30:04 | 500 |  4.456643885s |                 | MOVE     "/dav/InfiniCLOUD/utasch/Others/新建文件夹/"
[GIN] 2023/05/07 - 23:30:06 | 200 |  2.312470469s |   192.168.23.98 | POST     "/api/fs/list"
ERRO[2023-05-07 23:30:08] failed rename /InfiniCLOUD/utasch/Others/新建文件夹 to Inuyasha: MOVE /Others/新建文件夹: 200
github.com/alist-org/alist/v3/internal/op.Rename
	/app/internal/op/fs.go:412
github.com/alist-org/alist/v3/internal/fs.rename
	/app/internal/fs/other.go:40
github.com/alist-org/alist/v3/internal/fs.Rename
	/app/internal/fs/fs.go:81
github.com/alist-org/alist/v3/server/webdav.moveFiles
	/app/server/webdav/file.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
	/app/server/webdav/webdav.go:459
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:67
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172 
ERRO[2023-05-07 23:30:08] MOVE /dav/InfiniCLOUD/utasch/Others/新建文件夹/ MOVE /Others/新建文件夹: 200
github.com/alist-org/alist/v3/internal/op.Rename
	/app/internal/op/fs.go:412
github.com/alist-org/alist/v3/internal/fs.rename
	/app/internal/fs/other.go:40
github.com/alist-org/alist/v3/internal/fs.Rename
	/app/internal/fs/fs.go:81
github.com/alist-org/alist/v3/server/webdav.moveFiles
	/app/server/webdav/file.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
	/app/server/webdav/webdav.go:459
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:67
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172 
[GIN] 2023/05/07 - 23:30:08 | 500 |  752.658241ms |                 | MOVE     "/dav/InfiniCLOUD/utasch/Others/新建文件夹/"
[GIN] 2023/05/07 - 23:30:15 | 207 |     917.504µs |                 | PROPFIND  "/dav/InfiniCLOUD/"
[GIN] 2023/05/07 - 23:30:16 | 207 |     891.212µs |                 | PROPFIND  "/dav/InfiniCLOUD/utasch/Others/"
```

**part 2:**

```
ERRO[2023-05-07 23:30:32] failed get /InfiniCLOUD: can't find storage with rawPath: /InfiniCLOUD
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/app/internal/op/path.go:22
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:25
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:37
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:596
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:73
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172
failed get storage 
ERRO[2023-05-07 23:30:32] PROPFIND /dav/InfiniCLOUD/ can't find storage with rawPath: /InfiniCLOUD
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/app/internal/op/path.go:22
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:25
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:37
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:596
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:73
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172
failed get storage 
[GIN] 2023/05/07 - 23:30:32 | 405 |    1.603882ms |                 | PROPFIND  "/dav/InfiniCLOUD/"
ERRO[2023-05-07 23:30:32] failed get /InfiniCLOUD/utasch/Others: can't find storage with rawPath: /InfiniCLOUD/utasch/Others
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/app/internal/op/path.go:22
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:25
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:37
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:596
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:73
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1991
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172
failed get storage
```
